### ISSUE TITLE
[WIP] V2 Roadmap

### ISSUE THREAD

**Issue by joshuaavalon** [joshuaavalon/docker-cloudflare#23]
## New Features
* [x] Migrate to scoped API tokens. (#22) For details, please refer to [Cloudflare blog][api-token].
* [x] Support multiple domains. Due to popular demand, I decide to make it support multiple domains.
* [x] Support configuration file. While it is possible to support multiple domains in environment variables, it increases the complexity greatly. It also allow users to set proper permission on configuration.
* [x] Allow custom user and group for the process.
* [ ] Add webhook to notice monitoring service.

## Breaking Changes
* [x] Deprecate global API key. It will be able to use with warning, but it will be removed in the futures.

## Development
* [x] Move away from bash script. Due to increase complexity of the project, bash script is hard to maintain.
* [x] Migrate to GitHub Actions.
* [ ] Add unit tests.
* [x] Add GitHub issue templates.
* [x] Use semantic-release.

Because of the features changes, this project will no longer aim to be the smallest docker image (i.e. using minimum amount of libraries) but it will still try to be as small as possible.

If you have any features suggestions, you are welcome to comment below.

[api-token]: https://blog.cloudflare.com/api-tokens-general-availability/
